  name: üç∫ sync
      
  # Controls when the workflow will run
  on:
    # Triggers the workflow on push events but only for listed branches
    push:
      branches: [main]
      
    workflow_dispatch:
    
  # Cancel the current run if a new run is triggered
  concurrency:
    group: CI-${{ github.ref }}-1
    cancel-in-progress: true 

  jobs:
    createPullRequest:

      runs-on: ubuntu-latest
      
      steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: feature/melbourne-time-zone

      - name: Set git user
        run: |
          git config --global user.email "justin.liu@jhg.com.au"
          git config --global user.name "justin-jhg"

      - name: Merge Changes from Master to Melbourne Branch
        continue-on-error: true
        run: |
          git push origin --delete Melbourne
          git checkout -b Melbourne
          git push --set-upstream origin Melbourne
          git pull
          git merge -X theirs origin/main --allow-unrelated-histories --no-edit
                
      - name: Rebuild Melbourne Branch
        run: |
          npm install all
          npm run all
          git add .
          git commit -m "Rebuild Melbourne branch"
          git push 

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
          --title "merge changes into melbourne-time-zone" \
          --body "This pull request was automatically created by a GitHub Action to merge the latest changes main branch" \
          --base feature/melbourne-time-zone \
          --head Melbourne
